import JSZip from "jszip";
import { format } from "date-fns";
import { PolicyStatus, type Prisma } from "@/generated/prisma";
import { buildEvidenceWhere } from "@/lib/evidence-list-filters";
import {
  initialProgressSteps,
  normalizeAuditPackageSections,
  type AuditPackageSectionId,
  type AuditProgressStep,
} from "@/lib/audit-package-sections";
import { prisma } from "@/lib/prisma";
import { renderRiskAssessmentPdfBuffer } from "@/lib/render-risk-assessment-pdf";
import { getObjectFromS3, putObjectToS3 } from "@/lib/s3";

const S3_FETCH_CONCURRENCY = 8;

export type AuditPackageProgressReporter = (
  steps: AuditProgressStep[],
  currentStep: string | null
) => Promise<void>;

export type AuditPackageInput = {
  organizationId: string;
  exportJobId: string;
  from: Date;
  to: Date;
  controlRefs?: string[];
  sections?: string[];
  onProgress?: AuditPackageProgressReporter;
};

export type AuditPackageResult = {
  s3Key: string;
  evidenceCount: number;
  evidenceSkipped: number;
  policyCount: number;
  hasRiskAssessment: boolean;
  baaCount: number;
  trainingCount: number;
  phiSystemCount: number;
  phiEdgeCount: number;
  auditLogCount: number;
};

type CsvRow = Record<string, string | number | boolean | null | undefined>;

type EvidenceRow = {
  id: string;
  title: string;
  s3Key: string | null;
  mimeType: string | null;
  collectedAt: Date;
  orgControl: { frameworkControl: { controlRef: string } };
};

type PolicyRow = {
  id: string;
  type: string;
  version: number;
  sourceS3Key: string | null;
  title: string;
};

export function escapeCsvValue(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return "";
  const str = String(value);
  if (/[",\n\r]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function rowsToCsv(headers: string[], rows: CsvRow[]): string {
  const lines = [headers.map(escapeCsvValue).join(",")];
  for (const row of rows) {
    lines.push(headers.map((h) => escapeCsvValue(row[h])).join(","));
  }
  return lines.join("\n") + "\n";
}

export function safeZipFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/^_+|_+$/g, "") || "file";
}

export function auditPackageS3Key(organizationId: string, exportJobId: string, at = new Date()): string {
  const day = format(at, "yyyy-MM-dd");
  return `orgs/${organizationId}/audit-packages/${day}-${exportJobId}.zip`;
}

export function buildAuditPackageReadme(params: {
  organizationName: string;
  exportedAt: Date;
  from: Date;
  to: Date;
  controlRefs: string[];
  evidenceCount: number;
  evidenceSkipped: number;
  policyCount: number;
  hasRiskAssessment: boolean;
  baaCount: number;
  trainingCount: number;
  phiSystemCount: number;
  phiEdgeCount: number;
  auditLogCount: number;
}): string {
  const controlFilter =
    params.controlRefs.length > 0
      ? params.controlRefs.join(", ")
      : "All controls (no filter)";

  return `# HIPAA Audit Package

**Organization:** ${params.organizationName}
**Exported at:** ${params.exportedAt.toISOString()}
**Evidence / audit-log date range:** ${params.from.toISOString()} — ${params.to.toISOString()}
**Control filter:** ${controlFilter}

## Contents

| Artifact | Count / status |
| --- | --- |
| Evidence files | ${params.evidenceCount} included (${params.evidenceSkipped} skipped — no S3 object) |
| Approved policies | ${params.policyCount} |
| Approved risk assessment | ${params.hasRiskAssessment ? "Included" : "None approved"} |
| BAA inventory (CSV) | ${params.baaCount} rows |
| Training records (CSV) | ${params.trainingCount} rows |
| PHI systems (CSV) | ${params.phiSystemCount} systems / ${params.phiEdgeCount} flows |
| Audit log (CSV) | ${params.auditLogCount} rows |

## Inclusion rules

- **Policies:** Only records with status \`APPROVED\` (PDF from S3).
- **Risk assessment:** Only the latest \`APPROVED\` assessment, rendered as PDF.
- **Evidence:** Valid evidence in the selected date range (and optional control refs) with an S3 file.
- **BAA inventory / training / PHI map:** Full organization inventories at export time.
- **Audit log:** Entries in the same date range as evidence.

Generated by CyberGuardIntel.
`;
}

async function mapPool<T, R>(
  items: T[],
  concurrency: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;

  async function worker(): Promise<void> {
    while (next < items.length) {
      const index = next++;
      results[index] = await fn(items[index]);
    }
  }

  const workers = Array.from(
    { length: Math.min(concurrency, Math.max(items.length, 1)) },
    () => worker()
  );
  await Promise.all(workers);
  return results;
}

function fileNameFromS3Key(s3Key: string, fallback: string): string {
  const base = s3Key.split("/").pop() || fallback;
  return safeZipFileName(base);
}

function includesSection(
  sections: AuditPackageSectionId[],
  id: AuditPackageSectionId
): boolean {
  return sections.includes(id);
}

export async function buildAndUploadAuditPackage(
  input: AuditPackageInput
): Promise<AuditPackageResult> {
  const controlRefs = input.controlRefs?.filter(Boolean) ?? [];
  const sections = normalizeAuditPackageSections(input.sections);
  let steps = initialProgressSteps(sections);

  const markRunning = async (stepId: string) => {
    steps = steps.map((s) => {
      if (s.id === stepId) return { ...s, status: "running" };
      if (s.status === "running") return { ...s, status: "done" };
      return s;
    });
    if (input.onProgress) await input.onProgress(steps, stepId);
  };

  const markDone = async (stepId: string) => {
    steps = steps.map((s) =>
      s.id === stepId ? { ...s, status: "done" } : s
    );
    if (input.onProgress) await input.onProgress(steps, stepId);
  };

  await markRunning("load");

  const org = await prisma.organization.findUniqueOrThrow({
    where: { id: input.organizationId },
    select: { id: true, name: true },
  });

  const evidenceWhere = buildEvidenceWhere({
    organizationId: input.organizationId,
    collectedFrom: input.from,
    collectedTo: input.to,
    ...(controlRefs.length > 0 ? { controlRefs } : {}),
  });

  const wantEvidence = includesSection(sections, "evidence");
  const wantPolicies = includesSection(sections, "policies");
  const wantRisk = includesSection(sections, "risk_assessment");
  const wantBaa = includesSection(sections, "baa");
  const wantTraining = includesSection(sections, "training");
  const wantPhiMap = includesSection(sections, "phi_map");
  const wantAuditLog = includesSection(sections, "audit_log");

  const [
    evidenceRows,
    policies,
    riskAssessment,
    baaRecords,
    trainingRecords,
    phiSystems,
    phiEdges,
    auditLogs,
  ] = await Promise.all([
      wantEvidence
        ? (prisma.evidence.findMany({
            where: evidenceWhere,
            select: {
              id: true,
              title: true,
              s3Key: true,
              mimeType: true,
              collectedAt: true,
              orgControl: {
                select: {
                  frameworkControl: { select: { controlRef: true } },
                },
              },
            },
            orderBy: { collectedAt: "desc" },
          }) as Promise<EvidenceRow[]>)
        : Promise.resolve([] as EvidenceRow[]),
      wantPolicies
        ? (prisma.policy.findMany({
            where: {
              organizationId: input.organizationId,
              status: PolicyStatus.APPROVED,
              sourceS3Key: { not: null },
            },
            select: {
              id: true,
              type: true,
              version: true,
              sourceS3Key: true,
              title: true,
            },
            orderBy: { type: "asc" },
          }) as Promise<PolicyRow[]>)
        : Promise.resolve([] as PolicyRow[]),
      wantRisk
        ? prisma.riskAssessment.findFirst({
            where: {
              organizationId: input.organizationId,
              status: PolicyStatus.APPROVED,
            },
            orderBy: [{ version: "desc" }, { approvedAt: "desc" }],
          })
        : Promise.resolve(null),
      wantBaa
        ? prisma.baaRecord.findMany({
            where: { organizationId: input.organizationId },
            orderBy: { vendorName: "asc" },
          })
        : Promise.resolve([]),
      wantTraining
        ? prisma.trainingRecord.findMany({
            where: { organizationId: input.organizationId },
            orderBy: [{ employeeName: "asc" }, { completedAt: "desc" }],
          })
        : Promise.resolve([]),
      wantPhiMap
        ? prisma.phiSystem.findMany({
            where: { organizationId: input.organizationId },
            orderBy: { name: "asc" },
          })
        : Promise.resolve([]),
      wantPhiMap
        ? prisma.phiFlowEdge.findMany({
            where: { organizationId: input.organizationId },
            orderBy: { createdAt: "asc" },
            include: {
              sourcePhiSystem: { select: { name: true } },
              targetPhiSystem: { select: { name: true } },
              targetIntegration: { select: { displayName: true, type: true } },
              viaIntegration: { select: { displayName: true, type: true } },
              baaRecord: { select: { vendorName: true, status: true } },
            },
          })
        : Promise.resolve([]),
      wantAuditLog
        ? prisma.auditLog.findMany({
            where: {
              organizationId: input.organizationId,
              createdAt: { gte: input.from, lte: input.to },
            },
            orderBy: { createdAt: "desc" },
          })
        : Promise.resolve([]),
    ]);

  await markDone("load");

  const zip = new JSZip();
  let evidenceCount = 0;
  let evidenceSkipped = 0;

  if (wantEvidence) {
    await markRunning("evidence");
    const withS3 = evidenceRows.filter((e) => e.s3Key);
    evidenceSkipped = evidenceRows.length - withS3.length;

    const evidenceFetched = await mapPool(withS3, S3_FETCH_CONCURRENCY, async (row) => {
      try {
        const obj = await getObjectFromS3(row.s3Key!);
        return { row, body: obj.body, ok: true as const };
      } catch {
        return { row, body: null, ok: false as const };
      }
    });

    const usedPaths = new Set<string>();
    for (const item of evidenceFetched) {
      if (!item.ok || !item.body) {
        evidenceSkipped += 1;
        continue;
      }
      const controlRef = safeZipFileName(
        item.row.orgControl.frameworkControl.controlRef
      );
      let fileName = fileNameFromS3Key(item.row.s3Key!, `${item.row.id}.bin`);
      let path = `evidence/${controlRef}/${fileName}`;
      let n = 1;
      while (usedPaths.has(path)) {
        const dot = fileName.lastIndexOf(".");
        const stem = dot > 0 ? fileName.slice(0, dot) : fileName;
        const ext = dot > 0 ? fileName.slice(dot) : "";
        fileName = `${stem}-${n}${ext}`;
        path = `evidence/${controlRef}/${fileName}`;
        n += 1;
      }
      usedPaths.add(path);
      zip.file(path, item.body);
      evidenceCount += 1;
    }
    await markDone("evidence");
  }

  let policyCount = 0;
  if (wantPolicies) {
    await markRunning("policies");
    const policyFetched = await mapPool(policies, S3_FETCH_CONCURRENCY, async (policy) => {
      const key = policy.sourceS3Key!;
      try {
        const obj = await getObjectFromS3(key);
        return { policy, body: obj.body, ok: true as const };
      } catch {
        return { policy, body: null, ok: false as const };
      }
    });

    for (const item of policyFetched) {
      if (!item.ok || !item.body) continue;
      const name = safeZipFileName(
        `${item.policy.type}-v${item.policy.version}.pdf`
      );
      zip.file(`policies/${name}`, item.body);
      policyCount += 1;
    }
    await markDone("policies");
  }

  let hasRiskAssessment = false;
  if (wantRisk) {
    await markRunning("risk_assessment");
    if (riskAssessment) {
      const pdfBytes = await renderRiskAssessmentPdfBuffer({
        assessment: riskAssessment,
        organizationName: org.name,
        approvedByName: null,
      });
      zip.file(
        `risk-assessment/risk-assessment-v${riskAssessment.version}.pdf`,
        pdfBytes
      );
      hasRiskAssessment = true;
    }
    await markDone("risk_assessment");
  }

  if (wantBaa || wantTraining || wantPhiMap || wantAuditLog) {
    await markRunning("csvs");
    if (wantBaa) {
      const baaCsv = rowsToCsv(
        [
          "id",
          "vendorName",
          "vendorEmail",
          "services",
          "status",
          "signedAt",
          "expiresAt",
          "notes",
        ],
        baaRecords.map((r) => ({
          id: r.id,
          vendorName: r.vendorName,
          vendorEmail: r.vendorEmail,
          services: r.services,
          status: r.status,
          signedAt: r.signedAt?.toISOString() ?? "",
          expiresAt: r.expiresAt?.toISOString() ?? "",
          notes: r.notes,
        }))
      );
      zip.file("baa-inventory.csv", baaCsv);
    }

    if (wantTraining) {
      const trainingCsv = rowsToCsv(
        [
          "id",
          "employeeId",
          "employeeName",
          "employeeEmail",
          "employeeJobTitle",
          "trainingTitle",
          "completedAt",
          "nextDueAt",
        ],
        trainingRecords.map((r) => ({
          id: r.id,
          employeeId: r.employeeId,
          employeeName: r.employeeName,
          employeeEmail: r.employeeEmail,
          employeeJobTitle: r.employeeJobTitle,
          trainingTitle: r.trainingTitle,
          completedAt: r.completedAt.toISOString(),
          nextDueAt: r.nextDueAt.toISOString(),
        }))
      );
      zip.file("training-records.csv", trainingCsv);
    }

    if (wantPhiMap) {
      const systemsCsv = rowsToCsv(
        [
          "id",
          "name",
          "systemType",
          "containsPhi",
          "phiTypes",
          "encryptionAtRest",
          "encryptionInTransit",
          "baaRecordId",
          "description",
        ],
        phiSystems.map((s) => ({
          id: s.id,
          name: s.name,
          systemType: s.systemType,
          containsPhi: s.containsPhi,
          phiTypes: s.phiTypes.join("; "),
          encryptionAtRest: s.encryptionAtRest,
          encryptionInTransit: s.encryptionInTransit,
          baaRecordId: s.baaRecordId,
          description: s.description,
        }))
      );
      zip.file("phi-systems.csv", systemsCsv);

      const edgesCsv = rowsToCsv(
        [
          "id",
          "sourceSystem",
          "targetSystem",
          "targetIntegration",
          "viaIntegration",
          "isExternalVendorFlow",
          "dataClassification",
          "baaVendor",
          "baaStatus",
        ],
        phiEdges.map((e) => ({
          id: e.id,
          sourceSystem: e.sourcePhiSystem.name,
          targetSystem: e.targetPhiSystem?.name ?? "",
          targetIntegration: e.targetIntegration
            ? `${e.targetIntegration.displayName} (${e.targetIntegration.type})`
            : "",
          viaIntegration: e.viaIntegration
            ? `${e.viaIntegration.displayName} (${e.viaIntegration.type})`
            : "",
          isExternalVendorFlow: e.isExternalVendorFlow,
          dataClassification: e.dataClassification,
          baaVendor: e.baaRecord?.vendorName ?? "",
          baaStatus: e.baaRecord?.status ?? "",
        }))
      );
      zip.file("phi-flow-edges.csv", edgesCsv);
    }

    if (wantAuditLog) {
      const auditCsv = rowsToCsv(
        [
          "id",
          "actorId",
          "actorEmail",
          "action",
          "resourceType",
          "resourceId",
          "ipAddress",
          "createdAt",
        ],
        auditLogs.map((r) => ({
          id: r.id,
          actorId: r.actorId,
          actorEmail: r.actorEmail,
          action: r.action,
          resourceType: r.resourceType,
          resourceId: r.resourceId,
          ipAddress: r.ipAddress,
          createdAt: r.createdAt.toISOString(),
        }))
      );
      zip.file("audit-log.csv", auditCsv);
    }
    await markDone("csvs");
  }

  const exportedAt = new Date();
  if (includesSection(sections, "readme")) {
    await markRunning("readme");
    const readme = buildAuditPackageReadme({
      organizationName: org.name,
      exportedAt,
      from: input.from,
      to: input.to,
      controlRefs,
      evidenceCount,
      evidenceSkipped,
      policyCount,
      hasRiskAssessment,
      baaCount: baaRecords.length,
      trainingCount: trainingRecords.length,
      phiSystemCount: phiSystems.length,
      phiEdgeCount: phiEdges.length,
      auditLogCount: auditLogs.length,
    });
    zip.file("README.md", readme);
    await markDone("readme");
  }

  await markRunning("upload");
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  const s3Key = auditPackageS3Key(input.organizationId, input.exportJobId, exportedAt);
  await putObjectToS3(s3Key, zipBuffer, "application/zip", {
    "org-id": input.organizationId,
    "export-job-id": input.exportJobId,
  });
  await markDone("upload");

  return {
    s3Key,
    evidenceCount,
    evidenceSkipped,
    policyCount,
    hasRiskAssessment,
    baaCount: baaRecords.length,
    trainingCount: trainingRecords.length,
    phiSystemCount: phiSystems.length,
    phiEdgeCount: phiEdges.length,
    auditLogCount: auditLogs.length,
  };
}

/** Serialize progress steps for Prisma Json column. */
export function progressStepsToJson(
  steps: AuditProgressStep[]
): Prisma.InputJsonValue {
  return steps as unknown as Prisma.InputJsonValue;
}
