import manifest from "../../public/integrations/icons/manifest.json";

import type { IntegrationCatalogEntry } from "@/lib/integration-catalog";

/** Local paths to downloaded brand icons (generated by scripts/download-integration-icons.mjs). */
export const INTEGRATION_ICON_PATHS: Record<string, string> = manifest;

export function getIntegrationIconPath(id: string): string | undefined {
  return INTEGRATION_ICON_PATHS[id];
}

export function hasIntegrationIcon(id: string): boolean {
  return id in INTEGRATION_ICON_PATHS;
}

export type IntegrationIconTarget = {
  id: string;
  name: string;
  letter: string;
  color: string;
  bg: string;
};

export function toIconTarget(
  entry: IntegrationCatalogEntry
): IntegrationIconTarget {
  return {
    id: entry.id,
    name: entry.name,
    letter: entry.letter,
    color: entry.color,
    bg: entry.bg,
  };
}

export function toIconTargetFromType(
  type: string,
  displayName: string,
  entry?: IntegrationCatalogEntry
): IntegrationIconTarget {
  return {
    id: type,
    name: displayName,
    letter: entry?.letter ?? displayName[0] ?? "?",
    color: entry?.color ?? "#111",
    bg: entry?.bg ?? "#F1EFE8",
  };
}
