import { generateBaaMarkdownPdf } from "@/lib/baa-markdown-pdf";

export async function generatePolicyMarkdownPdf(input: {
  title: string;
  markdown: string;
}): Promise<Uint8Array> {
  return generateBaaMarkdownPdf({
    title: input.title,
    markdown: input.markdown,
    footer: "Approved HIPAA policy — generated by CyberGuardIntel",
  });
}

export function policyApprovedPdfS3Key(
  organizationId: string,
  policyId: string,
  version: number
): string {
  return `hipaa/policies/${organizationId}/${policyId}-v${version}-approved.pdf`;
}

export function policyApprovedPdfFileName(
  policyType: string,
  version: number
): string {
  const slug = policyType.toLowerCase().replace(/_/g, "-");
  return `${slug}-v${version}.pdf`;
}
