-- Expand PolicyType to 18 HIPAA Security Rule policies (CGI standard set)
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'SECURITY_MANAGEMENT_PROCESS';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'ASSIGNED_SECURITY_RESPONSIBILITY';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'WORKFORCE_SECURITY';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'PERIODIC_EVALUATION';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'PERSON_ENTITY_AUTHENTICATION';
ALTER TYPE "PolicyType" ADD VALUE IF NOT EXISTS 'POLICIES_PROCEDURES_DOCUMENTATION';
